server:
  port: 8083
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/capstone
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8083/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

app:
  kafka:
    topics:
      jfc-unified: job-topic
      scan-destination: jfc-tool-topic
      update-destination: jfc-bgjobs-topic1
      ticket-destination: jfc-bgjobs-topic1